In [3]:
import pandas as pd
from pathlib import Path

# change this to your folder
base = Path("/Users/tonyvo/Desktop/Thesis/netlogo/data")

files = {
    "nodes": base / "roads" / "roads_nodes.csv",
    "edges": base / "roads" / "roads_from_to.csv",
    "places": base / "places" / "places.csv",
}

In [7]:
for name, path in files.items():
    print("\n" + "="*80)
    print(f"{name.upper()} -> {path}")
    print("="*80)

    df = pd.read_csv(path)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nDtypes:")
    print(df.dtypes)

    print("\nMissing values:")
    print(df.isna().sum())

    print("\nFirst 5 rows:")
    display(df.head())

    print("\nSample values per column:")
    for col in df.columns:
        vals = df[col].dropna().astype(str).head(3).tolist()
        print(f"{col}: {vals}")

================================================================================
NODES -> /Users/tonyvo/Desktop/Thesis/netlogo/data/roads/roads_nodes.csv
================================================================================

Shape:
(173095, 15)

Columns:
['osm_id', 'code', 'fclass', 'name', 'ref', 'oneway', 'maxspeed', 'layer', 'bridge', 'tunnel', 'edge_id', 'ORIG_FID', 'node_id', 'x', 'y']

Dtypes:
osm_id        int64
code          int64
fclass       object
name         object
ref          object
oneway       object
maxspeed      int64
layer       float64
bridge       object
tunnel       object
edge_id     float64
ORIG_FID      int64
node_id       int64
x           float64
y           float64
dtype: object

Missing values:
osm_id      0
code        0
fclass      0
name        0
ref         0
oneway      0
maxspeed    0
layer       0
bridge      0
tunnel      0
edge_id     0
ORIG_FID    0
node_id     0
x           0
y           0
dtype: int64

First 5 rows:

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,edge_id,ORIG_FID,node_id,x,y
0,953734440,5147,track_grade5,,,B,0,0.0,F,F,118693.0,118693,1,125951.0740,475615.8302
1,7391647,5115,tertiary,Aalsmeerderweg,,B,50,0.0,F,F,118694.0,118694,3,113223.2327,476246.3143
2,7391647,5115,tertiary,Aalsmeerderweg,,B,50,0.0,F,F,118694.0,118694,4,113598.8932,476458.6950
3,147571321,5121,unclassified,Polderweg,,B,60,0.0,F,F,118695.0,118695,5,125816.9304,475188.7586
4,147571321,5121,unclassified,Polderweg,,B,60,0.0,F,F,118695.0,118695,6,125539.0609,476460.8473

Sample values per column:
osm_id: ['953734440', '7391647', '7391647']
code: ['5147', '5115', '5115']
fclass: ['track_grade5', 'tertiary', 'tertiary']
name: [' ', 'Aalsmeerderweg', 'Aalsmeerderweg']
ref: [' ', ' ', ' ']
oneway: ['B', 'B', 'B']
maxspeed: ['0', '50', '50']
layer: ['0.0', '0.0', '0.0']
bridge: ['F', 'F', 'F']
tunnel: ['F', 'F', 'F']
edge_id: ['118693.0', '118694.0', '118694.0']
ORIG_FID: ['118693', '118694', '118694']
node_id: ['1', '3', '4']
x: ['125951.07400000095', '113223.23270000143', '113598.89319999889']
y: ['475615.8302000016', '476246.3143000007', '476458.69500000024']

================================================================================
EDGES -> /Users/tonyvo/Desktop/Thesis/netlogo/data/roads/roads_from_to.csv
================================================================================

Shape:
(242649, 18)

Columns:
['edge_id', 'osm_id', 'code', 'fclass', 'name', 'ref', 'oneway', 'maxspeed', 'layer', 'bridge', 'tunnel', 'Shape_Length', 'start_x', 'start_y', 'end_x', 'end_y', 'from_id', 'to_id']

Dtypes:
edge_id         float64
osm_id            int64
code              int64
fclass           object
name             object
ref              object
oneway           object
maxspeed          int64
layer           float64
bridge           object
tunnel           object
Shape_Length    float64
start_x         float64
start_y         float64
end_x           float64
end_y           float64
from_id           int64
to_id             int64
dtype: object

Missing values:
edge_id         0
osm_id          0
code            0
fclass          0
name            0
ref             0
oneway          0
maxspeed        0
layer           0
bridge          0
tunnel          0
Shape_Length    0
start_x         0
start_y         0
end_x           0
end_y           0
from_id         0
to_id           0
dtype: int64

First 5 rows:

,edge_id,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,Shape_Length,start_x,start_y,end_x,end_y,from_id,to_id
0,118693.0,953734440,5147,track_grade5,,,B,0,0.0,F,F,42.434735,125951.0740,475615.8302,125951.0740,475615.8302,1,1
1,118694.0,7391647,5115,tertiary,Aalsmeerderweg,,B,50,0.0,F,F,431.576976,113223.2327,476246.3143,113598.8932,476458.6950,3,4
2,118695.0,147571321,5121,unclassified,Polderweg,,B,60,0.0,F,F,1389.800573,125816.9304,475188.7586,125539.0609,476460.8473,5,6
3,118696.0,7391647,5115,tertiary,Aalsmeerderweg,,B,50,0.0,F,F,48.283123,113598.8932,476458.6950,113640.9380,476482.4329,4,8
4,118697.0,334983205,5122,residential,Zilverschoonlaan,,B,30,0.0,F,F,181.908961,117328.2399,476543.2325,117492.7812,476465.6870,9,10

Sample values per column:
edge_id: ['118693.0', '118694.0', '118695.0']
osm_id: ['953734440', '7391647', '147571321']
code: ['5147', '5115', '5121']
fclass: ['track_grade5', 'tertiary', 'unclassified']
name: [' ', 'Aalsmeerderweg', 'Polderweg']
ref: [' ', ' ', ' ']
oneway: ['B', 'B', 'B']
maxspeed: ['0', '50', '60']
layer: ['0.0', '0.0', '0.0']
bridge: ['F', 'F', 'F']
tunnel: ['F', 'F', 'F']
Shape_Length: ['42.434735330205584', '431.5769758136337', '1389.8005728863575']
start_x: ['125951.07400000095', '113223.23270000143', '125816.93039999902']
start_y: ['475615.8302000016', '476246.3143000007', '475188.75860000023']
end_x: ['125951.07400000095', '113598.89319999889', '125539.060899999']
end_y: ['475615.8302000016', '476458.69500000024', '476460.8473000005']
from_id: ['1', '3', '5']
to_id: ['1', '4', '6']

================================================================================
PLACES -> /Users/tonyvo/Desktop/Thesis/netlogo/data/places/places.csv
================================================================================

Shape:
(3702, 5)

Columns:
['id', 'NEAR_FID', 'NEAR_DIST', 'x', 'y']

Dtypes:
id            object
NEAR_FID       int64
NEAR_DIST    float64
x            float64
y            float64
dtype: object

Missing values:
id           0
NEAR_FID     0
NEAR_DIST    0
x            0
y            0
dtype: int64

First 5 rows:

        id  NEAR_FID  NEAR_DIST            x            y
0  4366722    307760  22.439148  123203.2097  485916.9237
1  4376560    333410  32.842509  122407.2095  486772.2775
2  4754220    232860  10.587129  119464.0840  484254.2656
3  4842719    283407  37.647797  118474.6676  485395.8845
4  4842723    274447  29.579592  118506.8791  485147.9962

Sample values per column:
id: ['4366722', '4376560', '4754220']
NEAR_FID: ['307760', '333410', '232860']
NEAR_DIST: ['22.43914823477092', '32.84250933847523', '10.58712902990418']
x: ['123203.20969999954', '122407.20949999988', '119464.08399999885']
y: ['485916.92370000103', '486772.2774999999', '484254.2655999996']

In [12]:
nodes_path = base / "roads" / "roads_nodes.csv"
nodes = pd.read_csv(nodes_path)

nodes_clean = nodes[["node_id", "x", "y"]].copy()

nodes_clean.to_csv(base / "roads" / "roads_nodes_clean.csv", index=False)

In [11]:
edges_path = base / "roads" / "roads_from_to.csv"
edges = pd.read_csv(edges_path)

edges_clean = edges[["edge_id", "from_id", "to_id", "Shape_Length"]].copy()

print(edges_clean.head())
print(edges_clean.dtypes)
print(edges_clean.isna().sum())
print("Duplicate edge_id:", edges_clean["edge_id"].duplicated().sum())

edges_clean.to_csv(base / "roads" / "edges_clean.csv", index=False)

    edge_id  from_id  to_id  Shape_Length
0  118693.0        1      1     42.434735
1  118694.0        3      4    431.576976
2  118695.0        5      6   1389.800573
3  118696.0        4      8     48.283123
4  118697.0        9     10    181.908961
edge_id         float64
from_id           int64
to_id             int64
Shape_Length    float64
dtype: object
edge_id         0
from_id         0
to_id           0
Shape_Length    0
dtype: int64
Duplicate edge_id: 0

In [10]:
places_path = base / "places" / "places.csv"
places = pd.read_csv(places_path)

places_clean = places[["id", "x", "y"]].copy()

print(places_clean.head())
print(places_clean.dtypes)
print(places_clean.isna().sum())

places_clean.to_csv(base / "places" / "places_clean.csv", index=False)

        id            x            y
0  4366722  123203.2097  485916.9237
1  4376560  122407.2095  486772.2775
2  4754220  119464.0840  484254.2656
3  4842719  118474.6676  485395.8845
4  4842723  118506.8791  485147.9962
id     object
x     float64
y     float64
dtype: object
id    0
x     0
y     0
dtype: int64