In [1]:
import pynetlogo
import pandas as pd
import itertools
from pathlib import Path

# 1. Explicitly point to the libjvm.dylib file inside NetLogo's application package
jvm_path = "/Applications/NetLogo 6.4.0/runtime/Contents/Home/lib/server/libjvm.dylib"

netlogo = pynetlogo.NetLogoLink(
    gui=False,
    netlogo_home="/Applications/NetLogo 6.4.0",
    jvm_path=jvm_path 
)

model_path = "/Users/tonyvo/Desktop/Thesis/netlogo/models/6.4.0/third_place_attributes.nlogo"

netlogo.load_model(model_path)
netlogo.command("setup")

observer: "Created 200 people"
observer: "Setup complete"

# Experiment 4: Preference and Third Place Attributes

In [2]:
parameter_grid = {
    "number-of-people": [200],
    "baseline-stop-probability": [30],
    "third-place-search-radius": [2],
    "route-third-place-sample-size": [50],
    "rigid-dwell-time": [30],
    "medium-dwell-time": [45],
    "flexible-dwell-time": [60],
    "encounter-odds-increment": [0.10],
    "encounter-weight": [5],
    "social-feedback?": [True],
    "attribute-based-choice?": [False, True]
}

reporters = [
    "visits-per-person",
    "average-stop-probability",
    "average-social-encounters",
    "average-social-odds-ratio",
    "total-co-presence",
    "co-presence-per-visit",
    "visited-places-count",
    "places-with-co-presence",
    "visit-concentration",
    "average-visited-place-affordability",
    "average-visited-place-welcomingness"
]

results = []

keys = list(parameter_grid.keys())
values = list(parameter_grid.values())

run_id = 0

for combination in itertools.product(*values):
    params = dict(zip(keys, combination))
    
    for seed in range(1, 21):  # 20 repetitions
        run_id += 1
        
        netlogo.command(f"random-seed {seed}")
        
        for parameter, value in params.items():
            if isinstance(value, bool):
                value = "true" if value else "false"
            netlogo.command(f"set {parameter} {value}")
        
        netlogo.command("setup")
        netlogo.command("repeat 1000 [ go ]")
        
        row = {
            "experiment": "attribute_test",
            "run_id": run_id,
            "seed": seed,
            **params,
        }
        
        for reporter in reporters:
            row[reporter] = netlogo.report(reporter)
        
        results.append(row)

exp2 = pd.DataFrame(results)

output_path = "/Users/tonyvo/Desktop/Thesis/netlogo/models/experiment_4_attributes.csv"
exp2.to_csv(output_path, index=False)

print(exp2.shape)
exp2.head()

observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
observer: "Created 200 people"
observer: "Setup complete"
(40, 25)

,experiment,run_id,seed,number-of-people,baseline-stop-probability,third-place-search-radius,route-third-place-sample-size,rigid-dwell-time,medium-dwell-time,flexible-dwell-time,...,average-stop-probability,average-social-encounters,average-social-odds-ratio,total-co-presence,co-presence-per-visit,visited-places-count,places-with-co-presence,visit-concentration,average-visited-place-affordability,average-visited-place-welcomingness
0,attribute_test,1,1,200,30,2,50,30,45,60,...,30.680673,6.80,1.5420,4745.0,12.104592,60.0,44.0,0.035714,0.540708,0.509095
1,attribute_test,2,2,200,30,2,50,30,45,60,...,29.815402,5.55,1.5110,4398.0,11.822581,59.0,45.0,0.032258,0.544554,0.552081
2,attribute_test,3,3,200,30,2,50,30,45,60,...,29.983067,5.35,1.4865,4284.0,11.933148,60.0,45.0,0.044568,0.559730,0.499314
3,attribute_test,4,4,200,30,2,50,30,45,60,...,29.577559,5.10,1.4800,4250.0,11.154856,60.0,42.0,0.036745,0.522701,0.504331
4,attribute_test,5,5,200,30,2,50,30,45,60,...,29.992369,6.20,1.5200,4531.0,12.482094,59.0,44.0,0.041322,0.450095,0.544913

In [3]:
off = exp2[exp2["attribute-based-choice?"] == False].iloc[0]
on = exp2[exp2["attribute-based-choice?"] == True].iloc[0]

comparison = pd.DataFrame({
    "metric": [
        "visits-per-person",
        "average-stop-probability",
        "average-social-encounters",
        "average-social-odds-ratio",
        "total-co-presence",
        "co-presence-per-visit",
        "visited-places-count",
        "places-with-co-presence",
        "visit-concentration",
        "average-visited-place-affordability",
        "average-visited-place-welcomingness"
    ],
    "attribute_based_choice_off": [
        off["visits-per-person"],
        off["average-stop-probability"],
        off["average-social-encounters"],
        off["average-social-odds-ratio"],
        off["total-co-presence"],
        off["co-presence-per-visit"],
        off["visited-places-count"],
        off["places-with-co-presence"],
        off["visit-concentration"],
        off["average-visited-place-affordability"],
        off["average-visited-place-welcomingness"]
    ],
    "attribute_based_choice_on": [
        on["visits-per-person"],
        on["average-stop-probability"],
        on["average-social-encounters"],
        on["average-social-odds-ratio"],
        on["total-co-presence"],
        on["co-presence-per-visit"],
        on["visited-places-count"],
        on["places-with-co-presence"],
        on["visit-concentration"],
        on["average-visited-place-affordability"],
        on["average-visited-place-welcomingness"]
    ],
})

comparison["absolute_change"] = comparison["attribute_based_choice_on"] - comparison["attribute_based_choice_off"]
comparison["percent_change"] = (
    comparison["absolute_change"] / comparison["attribute_based_choice_off"] * 100
)

comparison

,metric,attribute_based_choice_off,attribute_based_choice_on,absolute_change,percent_change
0,visits-per-person,1.960000,2.215000,0.255000,13.010204
1,average-stop-probability,30.680673,39.371625,8.690952,28.327124
2,average-social-encounters,6.800000,35.250000,28.450000,418.382353
3,average-social-odds-ratio,1.542000,2.277000,0.735000,47.665370
4,total-co-presence,4745.000000,14684.000000,9939.000000,209.462592
5,co-presence-per-visit,12.104592,33.146727,21.042135,173.835973
6,visited-places-count,60.000000,26.000000,-34.000000,-56.666667
7,places-with-co-presence,44.000000,18.000000,-26.000000,-59.090909
8,visit-concentration,0.035714,0.119639,0.083925,234.988713
9,average-visited-place-affordability,0.540708,0.715495,0.174787,32.325536
10,average-visited-place-welcomingness,0.509095,0.729757,0.220662,43.344091